//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaravanInstructor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public action()
        {
            this.procedure = new HashSet<procedure>();
        }
    
        public int action_id { get; set; }
        public string name { get; set; }
        public int data_type_1_id { get; set; }
        public string data_1 { get; set; }
        public Nullable<int> data_type_2_id { get; set; }
        public string data_2 { get; set; }
    
        public virtual data_type data_type { get; set; }
        public virtual data_type data_type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procedure> procedure { get; set; }
    }
}
