//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaravanInstructor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class attribute
    {
        public int attribute_id { get; set; }
        public string name { get; set; }
        public int data_type_id { get; set; }
    
        public virtual data_type data_type { get; set; }
    }
}
