//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaravanInstructor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercise
    {
        public int exercise_id { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string instructor_comment { get; set; }
        public int procedure_id { get; set; }
        public bool approved { get; set; }
        public int report_id { get; set; }
    
        public virtual procedure procedure { get; set; }
        public virtual report report { get; set; }
    }
}
