//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaravanInstructor.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSimaer : DbContext
    {
        public DbSimaer()
            : base("name=DbSimaer")
        {
            this.Database.Connection.ConnectionString += ";Password=codaltec";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action> action { get; set; }
        public virtual DbSet<attribute> attribute { get; set; }
        public virtual DbSet<data_type> data_type { get; set; }
        public virtual DbSet<exercise> exercise { get; set; }
        public virtual DbSet<grade> grade { get; set; }
        public virtual DbSet<pilot> pilot { get; set; }
        public virtual DbSet<procedure> procedure { get; set; }
        public virtual DbSet<procedure_type> procedure_type { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<runway_tol> runway_tol { get; set; }
        public virtual DbSet<scenario> scenario { get; set; }
        public virtual DbSet<system> system { get; set; }
        public virtual DbSet<time_day> time_day { get; set; }
    }
}
